### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by m-a-flynn** [QuiCM/EventStopper#5]
With no releases and a limited description, it's difficult for me to figure out how to install this plugin. I'm new at this but I've successfully installed several plugins onto my tshock server, and placing the .dll files from EventStopper/bin/Release into the ServerPlugins folder throws several fatal errors. Am I missing something?

**Comment by m-a-flynn** [comment]
I am happy to write documentation or otherwise help with this process if you can help me get this plugin working on my server

**Comment by QuiCM** [comment]
What kind of errors were you receiving?
